version: "3"


services:
  
  nothing:
    container_name: idoor_c
    image: idoor_i
    build: .
    ports:
      - 8000:80
    restart: always

    volumes:
      - ./src:/var/www/html
    environment:
      - MYSQL_DATABASE=nothing_db
      - MYSQL_USER=nothing
      - MYSQL_PASSWORD=toor123!
      - MYSQL_ALLOW_EMPTY_PASSWORD=1

  db:
    image: mysql
    hostname: sqldb
    environment:
      - MYSQL_DATABASE=nothing_db
      - MYSQL_USER=nothing
      - MYSQL_PASSWORD=toor123!
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - "./db:/docker-entrypoint-initdb.d" # sync persistent sql files with container


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 6412:80
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
